spring:
  datasource: 
    druid: 
      url: jdbc:mysql://localhost:3306/yue_library_test?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 3000
yue:  api-version:    minimum-version: 1