spring:
  datasource:                                              # data-jdbc就是SpringJDBC的封装
    druid: 
      url: jdbc:mysql://localhost:3306/yue_library_test?characterEncoding=utf-8&useSSL=false
      username: root
      password: 02194096e7d840a992a2f627629a94da
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    username: admin
    password: 02194096e7d840a992a2f627629a94da            # 养成良好习惯，无论任何环境不使用弱密码
    uris:
      - https://localhost:30292
yue:
  api-version:
    minimum-version: 1
  web:
#    enabled-repeatedly-read-servlet-request: true
#    enabled-repeatedly-read-servlet-request: false
    http-message-converter:
      jackson:
        enabled: true
#        write-null-number-as-zero: true
#    http-message-converter:
#      fastjson:
#        enabled: true
  net:
    proxy:
      enabled: true
      http-server-enabled: true
      http-server-host: 127.0.0.1
      http-server-port: 80
      https-server-enabled: true
      https-server-host: 127.0.0.1
      https-server-port: 443
      ftp-server-enabled: true
      ftp-server-host: 127.0.0.1
      ftp-server-port: 80
      socks-server-enabled: true
      socks-server-host: 127.0.0.1
      socks-server-port: 1080
      socks-proxy-version: 5
      non-proxy-hosts: localhost|127.*|[::1]|0.0.0.0|[::0]
      non-proxy-hosts-additional: ai.ylyue.cn|*.ylyue.cn
      basic-authenticator-username: ylyue
      basic-authenticator-password: ylyue
  thread-pool:
    async:
      enabled: true                                         # 启用异步线程池
      thread-name-prefix: async-exec-                       # 线程池名的前缀
      core-pool-size: 10                                    # 核心线程数
      max-pool-size: 20                                     # 最大线程数
      queue-capacity: 200                                   # 任务队列容量（阻塞队列）
      allow-core-thread-time-out: false                     # 是否允许核心线程超时
      keep-alive-seconds: 60                                # 允许线程的空闲时间（单位：秒）
      wait-for-tasks-to-complete-on-shutdown: true          # 应用关闭时-是否等待未完成任务继续执行，再继续销毁其他的Bean
      await-termination-seconds: 5                          # 应用关闭时-继续等待时间（单位：秒）
      rejected-execution-handler-policy: caller_runs_policy # 线程池拒绝策略
      enable-servlet-async-context: true                    # 是否开启 ServletAsyncContext
      servlet-async-context-timeout-millis: 600             # ServletAsyncContext阻塞超时时长（单位：毫秒），异步上下文最长生命周期（最大阻塞父线程多久）

  jdbc:
    enable-boolean-map-recognition: true                    # 启用布尔值映射识别
    enable-delete-query-filter: true                        # 启用删除查询过滤（只对自动生成的查询sql生效）
    enable-field-naming-strategy-recognition: true          # 启用数据库字段命名策略识别
    database-field-naming-strategy: snake_case              # 数据库字段命名策略
    field-definition-uuid: uuid                             # 关键字段定义-无序主键名
    field-definition-sort-idx: sort_idx                     # 关键字段定义-排序
    field-definition-delete-time: delete_time               # 关键字段定义-数据删除标识
    data-encrypt-algorithm: AES                             # 缺省数据加密算法（仅当在表级未配置单独的加密算法时，以缺省值的方式生效）
    data-encrypt-key: 1234567890123456                      # 缺省数据加密密钥（仅当在表级未配置单独的加密密钥时，以缺省值的方式生效）
    data-encrypt-configs:                                   # 数据加密配置（key：表名，value：数据加密规则）
      data_encrypt:                                         # 数据库对应的表名
        data-encrypt-algorithm: AES                         # 当前表加密算法（未设置使用缺省值）
        data-encrypt-key: 1234567890123455                  # 当前表加密密钥（未设置使用缺省值）
        fieldNames:                                         # 加密字段
          - cellphone
          - password
      data_encrypt_2:                                       # 数据库对应的表名
        fieldNames:                                         # 加密字段
          - email
          - password
    data-audit-table-names:                                 # 数据审计表名
      - data_audit
      - data_audit2
    data-audit-properties:                                  # 数据审计属性
      field-name-create-user: create_user                   # 审计字段定义-创建人
      field_name_create_user_uuid: create_user_uuid         # 审计字段定义-创建人uuid
      field_name_create_time: create_time                   # 审计字段定义-创建时间
      field_name_update_user: update_user                   # 审计字段定义-更新人
      field_name_update_user_uuid: update_user_uuid         # 审计字段定义-更新人uuid
      field_name_update_time: update_time                   # 审计字段定义-更新时间
      field_name_delete_user: delete_user                   # 审计字段定义-删除人
      field_name_delete_user_uuid: delete_user_uuid         # 审计字段定义-删除人uuid
      field_name_delete_time: delete_time                   # 审计字段定义-删除时间戳