spring:
  datasource: 
    druid: 
      url: jdbc:mysql://localhost:3306/yue_library_template_boot?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
      username: root
      password: 123456