spring:
  mvc:    hiddenmethod:      filter:        enabled: true
  datasource: 
    druid: 
      url: jdbc:mysql://77.0.3.21:30200/ssc_demo?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
      username: root
      password: ssc-mysql-123456..
  redis:
    host: 77.0.3.21
    port: 30210
    password: i1.xThk^PZUksQ!I
#    druid: 
#      url: jdbc:mysql://192.168.3.51:30202/yue_library_test?characterEncoding=utf-8&useSSL=false
##      url: jdbc:mysql://localhost:3306/yue_library_test?characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
#  redis:
#    host: 192.168.3.51
#    port: 30191
#    timeout: 3000
  elasticsearch:
    rest:
      uris:      - https://77.0.3.21:30292
      username: admin
      password: pEzcu2c0hG84LkAyNgjg
yue:  api-version:    minimum-version: 1
  web:
#    http-message-converter:#      jackson:#        enabled: true
#        write-null-number-as-zero: true    http-message-converter:      fastjson:
        enabled: true