server:
  port: 8080
spring:
  application:
    name: yue-library-test
  profiles:
    group:
      "test": "yue-library-base,yue-library-data-jdbc,test-confidential"
#      "test": "test-confidential"
      "test-performance": "yue-library-base,yue-library-data-jdbc,test-confidential-performance"
    active: test

logging:
  level:
    ai.yue.library: debug