spring:
  datasource: 
    druid: 
      url: jdbc:mysql://localhost:3306/yue_library_test?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    rest:
      uris:
      - https://localhost:30292
      username: admin
      password: 123456
yue:
  api-version:
    minimum-version: 1
  web:
#    enabled-repeatedly-read-servlet-request: true
#    enabled-repeatedly-read-servlet-request: false
    http-message-converter:
      jackson:
        enabled: true
#        write-null-number-as-zero: true
#    http-message-converter:
#      fastjson:
#        enabled: true
  net:
    proxy:
      enabled: true
      http-server-enabled: true
      http-server-host: 127.0.0.1
      http-server-port: 80
      https-server-enabled: true
      https-server-host: 127.0.0.1
      https-server-port: 443
      ftp-server-enabled: true
      ftp-server-host: 127.0.0.1
      ftp-server-port: 80
      socks-server-enabled: true
      socks-server-host: 127.0.0.1
      socks-server-port: 1080
      socks-proxy-version: 5
      non-proxy-hosts: localhost|127.*|[::1]|0.0.0.0|[::0]
      non-proxy-hosts-additional: ai.ylyue.cn|*.ylyue.cn
      basic-authenticator-username: ylyue
      basic-authenticator-password: ylyue
  thread-pool:
    async:
      enabled: true
      thread-name-prefix: async-exec-
      core-pool-size: 10
      max-pool-size: 20
      queue-capacity: 200
      allow-core-thread-time-out: false
      keep-alive-seconds: 60
      wait-for-tasks-to-complete-on-shutdown: true
      await-termination-seconds: 5
      rejected-execution-handler-policy: caller_runs_policy
      enable-servlet-async-context: true
      servlet-async-context-timeout-millis: 600