spring:
  rabbitmq:
    addresses: localhost:5672 #服务器的地址和端口
    username: rabbitmq #用户名
    password: rabbitmq #密码

  cloud:
    function:
      definition: consumer; # 函数名称，对应服务中的注入的Bean
    stream:
      rabbit:
        bindings:
          producer-out-0:
            producer:
              exchangeType: direct
              delayedExchange: true
          consumer-in-0:
            consumer:
              exchangeType: direct
              delayedExchange: true
              bindingRoutingKey: delay-msg # 貌似有bug，不同版本都注意下这个routingKey配置，会导致成功发送却没有消费者的情况（org.springframework: debug日志级别查看详情）

      bindings:
        producer-out-0:
          destination: delay-msg
        consumer-in-0:
          destination: delay-msg
