spring:
  datasource: 
    druid: 
      url: jdbc:mysql://192.168.3.51:3310/yue_library_template_simple?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
#      url: jdbc:mysql://localhost:3306/yue_library_template_simple?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      filter: 
        slf4j:
          enabled: true
          statement-prepare-after-log-enabled: false
          statement-execute-query-after-log-enabled: false
          statement-executable-sql-log-enable: true
  redis:    host: 192.168.3.51
    port: 30191
yue:  crypto:    aes-keyt: AES/ECB/PKCS5Padding3306