spring:
  datasource: 
    druid: 
      url: jdbc:mysql://localhost:3306/yue_library_template_simple?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  redis:    host: localhost
    port: 6379
yue:  crypto:    aes-keyt: AES/ECB/PKCS5Padding3306