spring:
  config:
    activate:
      on-profile: yue-library-auth-client
  security:
    user:
      roles: ENDPOINT_ADMIN
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized