spring:
  config:
    activate:
      on-profile: yue-library-auth-service
  security:
    user:
      roles: ENDPOINT_ADMIN
management:
  endpoint:
    env:
      enabled: false
    heapdump:
      enabled: false
    threaddump:
      enabled: false
    httptrace:
      enabled: false
    health:
      show-details: when_authorized